# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3dcf66979878bf07dd8ec2d30d6175739b115cf20b10f302950c561f49066b535a332641b97eee48f0fd142b475f616ca364b2a6878c554330dc6e0f3359c4

test:
  secret_key_base: ea1c8dfa81b5512b588933e40824070569bb8f5a307e1e76ca5de9a1722d9d5a6028ffecd1bf03a84e1aec54c18a2d106c358a1234147abcef827f29f4fa4e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
